title: Yerbas
author: Yerbas
description: A peer-to-peer blockchain designed to handle the efficient creation and transfer of assets from one party to another. It's an open-source project based on Bitcoin

baseurl: ""

# social links
x_username: Yerbas-Endeavor
github_username:  The-Yerbas-Endeavor
rss: rss

show_excerpts: false

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - _pages/index.md
 - _pages/buy-yerbas.md
 - _pages/wallet.md
# - _pages/whitepaper.md
 - _pages/community.md
 - _pages/pools.md
 - _pages/about.md
# - _pages/assets.md
# - _pages/smartnodesetup.md

# Build settings
theme: minima
relative_permalinks: false

# Reading Files
include:
  - _pages
  - _posts
  - _wallets
  - _translations
  - _paperwallet

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default

plugins:
 - jekyll-feed
 - jekyll-seo-tag
